### ISSUE TITLE
Hash is appended to file name.

### ISSUE THREAD

**Issue by alee122** [theupdateframework/go-tuf#104]
I was running through the setup tutorial and after running "tuf commit" each file's hash was appended to the beginning of the file name, which doesn't match the tutorial. If that is the correct behavior it would be helpful to update the tutorial so that people don't dive into the code thinking there might be a bug to fix.

**Comment by lmars** [comment]
@alee122 you are correct, would you be willing to fix the tutorial and prefix the filenames with hashes?

**Comment by alee122** [comment]
Sure! Glad I asked because I reinstalled it a bunch of times thinking I was going crazy. What was the thought process behind your decision to deviate from the original TUF paper?

**Comment by titanous** [comment]
It's not a deviation, this is consistent snapshots: https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#7-consistent-snapshots

**Comment by alee122** [comment]
Oh I see, I was going off the 2010 paper (didn't realize it was _that_ old).

**Comment by alee122** [comment]
Would you rather I wrote ``<file_hash>.baz.txt`` or write out an actual hash? If I were to use an actual hash I would also show the creation of baz.txt so the hash would match a user set up if they followed the directions exactly.

**Comment by alee122** [comment]
Oops.

**Comment by lmars** [comment]
The docs use example shortened hashes for keys so perhaps just make up some similar shortened hashes for the files.
