### ISSUE TITLE
Plan to release go-tuf and roadmap

### ISSUE THREAD

**Issue by chuanbozhang-okta** [theupdateframework/go-tuf#114]
Is there a plan to release this? Also what is the roadmap planned.

**Comment by titanous** [comment]
Hi, we'd like to get it updated to the latest version of the spec, but haven't had time yet. If you want to help, you could backport changes from https://fuchsia.googlesource.com/third_party/go-tuf/

We consider it to be "released", what are you looking for there?

**Comment by erickt** [comment]
We finally merged in the fuchsia patches, and I've uploaded my outstanding patches in #122, #123, #124. I wrote these some time ago, so I wouldn't be surprised if we had to do some iteration on them to get them ready for landing. After they land, we'll need to implement delegation support, and any other missing features from the TUF spec. At that point we might be in a good spot for doing a go-tuf release.

**Comment by zwass** [comment]
@titanous there is no tagged release on GitHub and therefore (to a naive potential user such as myself) no way to understand the maturity/stability of the project.

@erickt It looks like you have merged some PRs recently, but I don't see recent progress on the PRs you linked above. This is not hugely concerning except for #124 which is going to move to a new major version of the TUF specification. Should we we expect this to cause backwards-incompatible changes for repositories and/or clients using the current `HEAD` of `master`?

When looking at implementing TUF for a new project this implementation seems compelling, but the stability and maturity are unclear.

**Comment by zwass** [comment]
Is there any recommendation as to whether to use this repository vs. https://fuchsia.googlesource.com/third_party/go-tuf/?

**Comment by znewman01** [comment]
>Also what is the roadmap planned.

There is now a [GitHub project](https://github.com/orgs/theupdateframework/projects/1) with a roadmap for the next release of go-tuf. 

> there is no tagged release on GitHub 

There are now version tags (`v0.3.0` is the latest at the time of this comment).

> Is there any recommendation as to whether to use this repository vs. https://fuchsia.googlesource.com/third_party/go-tuf/?

In general, Google `third_party` code is just vendored from some upstream. In this case, the Fuchsia project vendors *this* repository, so you should prefer to use [theupdateframework/go-tuf](https://github.com/theupdateframework/go-tuf).
