### ISSUE TITLE
Implementing a custom LocalStore

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#134]
Hi, I wanted to implement a custom LocalStore for a store on an OCI registry, but I ran into a problem because the parameter type is private

https://github.com/theupdateframework/go-tuf/blob/aee6270feb5596036edde4b6d7564fa17db811cb/repo.go#L39

I potentially could use the in-memory store and do some before/after conversion, but just wanted to see if it would be acceptable to make this public.

**Comment by trishankatdatadog** [comment]
I don't see an immediate problem. @lukpueh @shibumi any objections?
