### ISSUE TITLE
Support adding and committing files in one command

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#14]
If I have all the necessary keys locally, I should be able to do all of the following with one command:
- add staged files to the targets manifest
- sign the targets manifest
- update and sign snapshot manifest
- update and sign timestamp manifest
- commit

This could be supported with a commit flag, e.g. `tuf commit --add`

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first with less focus on providing a CLI client. There might be a CLI based on this, but it will live in a separate repository.
