### ISSUE TITLE
Verify that Remote Store Interface returns the correct error code for Not Found for s3

### ISSUE THREAD

**Issue by hosseinsia** [theupdateframework/go-tuf#147]
Some part of the code-based is based on the assumption that the Remote Store Interface implementation for S3 returns the correct error code (i.e., ErrMissingRemoteMetadata). This is of importance because S3 uses 403 as a response code instead of commonly used 404.   

This issue it to check whether that is the case and address that if it is not.

**Comment by rdimitrov** [comment]
Closing since the code base changed and is no longer valid.

Thanks for raising this! 👍
