### ISSUE TITLE
Update the fast forward recovery implementation

### ISSUE THREAD

**Issue by hosseinsia** [theupdateframework/go-tuf#149]
At the time of submitting the https://github.com/theupdateframework/go-tuf/pull/143 that updates root, there was another PR describing the fast forward recovery approach. 
The current implementation of the root update is based on the current state of that PR (https://github.com/mnm678/specification/tree/e50151d9df632299ddea364c4f44fe8ca9c10184)

Specifically, the part of the updateRoots that removes some metadata files based on the top-level key rotation might need to be updated upon any change in the fast-forward recovery pr.

**Comment by rdimitrov** [comment]
Closing since the code base changed and is no longer valid.

Thanks for raising this! 👍
