### ISSUE TITLE
Error from TUF while building orbit.

### ISSUE THREAD

**Issue by JodhwaniMadhur** [theupdateframework/go-tuf#152]
go run ./cmd/package --type=pkg --enroll-secret=+6fOMFntLWUrMphCww64WTXP2P7LWlWo --fleet-url=https://127.0.0.1:8080 --update-url=https://127.0.0.1:4443 —update-roots='[{"keytype":"ed25519","scheme":"ed25519","keyid_hash_algorithms":["sha256","sha512"],"keyval":{"public":"e2c20fe1c4abe6dcbccf02ef60f5117feb6b64d2f051b4a26a15b1e73922d0cc"}}]' --insecure

`Error: 2021-09-14T14:24:43+05:30 FTL package failed error="initialize updates: failed to init updater: init tuf client: tuf: failed to decode root.json: tuf: valid signatures did not meet threshold"
`

So i tried to run the above command while building orbit but TUF is giving me this output, what should I do? I am on an intel mac with macOS v11.5.2 and I have my certificates trusted by OS X but not the key for the https update server.

**Comment by trishankatdatadog** [comment]
Sorry, but what is orbit? We are not aware of it, and do not support it directly.

**Comment by JodhwaniMadhur** [comment]
Ok, so orbit is a wrapper of osquery which is a compiance and security tool to monitor hosts through a server and create logs of hosts for security, so the orbit uses `go-tuf` to update osquery at the hosts end, while creating a package of orbit, the tuf give the following errors as mentioned above.

**Comment by trishankatdatadog** [comment]
Understand, but this seems like an orbit problem, not necessarily a go-tuf problem. Would you please page them first instead? Thanks.
