### ISSUE TITLE
Why recast ErrUnknownTarget as ErrNotFound?

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/go-tuf#156]
It appears that [sometimes](https://github.com/theupdateframework/go-tuf/pull/146#discussion_r710291805), the client API recasts `ErrUnknownTarget` as `ErrNotFound`. This seems unnecessary: there should be only one canonical error.

**Comment by rdimitrov** [comment]
Closing since the code base changed and so this is no longer valid.

Thanks for raising this! 👍
