### ISSUE TITLE
Multiple key ids for a key.PublicKey

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#158]
Brought up in review of https://github.com/theupdateframework/go-tuf/pull/148#discussion_r717159404

go-tuf holds a list of KEY IDs for a given key, but in practice, this only returns a single string. The python implementation also includes only one key id generated by https://github.com/secure-systems-lab/securesystemslib/blob/9b3ea003ab93ab6909d1327dfb2ab7af0309e7cc/securesystemslib/keys.py#L563

Was there a reason for this? If not, I can handle cleaning this up after #148

@hosseinsia

**Comment by asraa** [comment]
From @trishankatdatadog 

> Yeah, this could be related to the old key_hashing_algorithms kerfuffle (TLDR: we allowed using SHA2-256 and/or SHA2-512 to compute different, collision-resistant keyids for the same key).

**Comment by znewman01** [comment]
@asraa to reroute

**Comment by rdimitrov** [comment]
Closing since the code base changed and so it is no longer valid. 

Thanks for raising this! 👍
