### ISSUE TITLE
Set up versioned releases

### ISSUE THREAD

**Issue by ethan-lowman-dd** [theupdateframework/go-tuf#200]
We are still pre-1.0, but we need to give users a way to know when breaking changes are made and upgrade accordingly.

As discussed in the TUF community meeting, we intend to version pre-1.0 releases as v0.x.y, where x is incremented for breaking changes.

We will build release notes from a changelog file, updated in each PR as necessary. Changes will be tagged by sub-system, like `[client]`, `[cli]`, or similar.

A PR review checklist may help with the process.

**Comment by shibumi** [comment]
Note: We have a PR for releases via goreleaser and goreleaser can handle pre-releases + generate changelogs. It really makes sense to have a closer look on my PR here and maybe get this done for the first release: 

https://github.com/theupdateframework/go-tuf/pull/157

**Comment by shibumi** [comment]
If needed I can provide a test release in my fork, so that you can have a look at it and  we discuss changes etc

**Comment by joshuagl** [comment]
Cross-referencing an older issue where the need for releases is discussed https://github.com/theupdateframework/go-tuf/issues/114

**Comment by zwass** [comment]
Glad to see that this has been addressed!
