### ISSUE TITLE
Contributing guidelines link redirects to an unrelated page

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#212]
The current [contributing guidelines](https://github.com/theupdateframework/go-tuf/blob/2c5d73bebc1c8df9c7ac12e092cd4d60691b4448/CONTRIBUTING.md) link to the Flynn contributing guide. However, [the link](https://flynn.io/docs/contributing) redirects to the root of the archived [flynn/flynn repository](https://github.com/flynn/flynn).

We could change the link to point to [CONTRIBUTING.md in flynn/flynn](https://github.com/flynn/flynn/blob/master/CONTRIBUTING.md), but I'm not entirely sure that's appropriate:

1. There's a lot of references to the Flynn team, IRC channel, etc.
2. Some of the practices (e.g., "Ensure that each commit has a subsystem prefix (ex: `controller:`)", DCO) aren't being followed.

I can write a quick CONTRIBUTING.md file including:

- intro: we welcome contributions etc.
- PR procedure, LGTM requirement, etc.
  - Go/project specific guidelines: `gofmt -s`, `go test ./...`
- TUF code of conduct (which just points to the [CNCF code of conduct](https://github.com/theupdateframework/python-tuf/blob/develop/docs/CODE-OF-CONDUCT.md))

if that sounds good.

**Comment by joshuagl** [comment]
Thanks for the report @znewman01! @asraa already started working on addressing this in https://github.com/theupdateframework/go-tuf/pull/190, would appreciate your feedback on her proposal there.
