### ISSUE TITLE
client: Deprecate the “tuf-client list” command

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#216]
Description:
- The `list` command for the go-tuf client implementation might not be very useful in the long term
- It’s okay to build a list with the available targets when there are only a few, but that wouldn’t be very practical in a real-world use case with a lot of delegations and targets

Proposed alternative solutions:
- Implement a dedicated `tuf-client search <target-name>` command returning true/false
- Use the existing `get` command, but introduce a `--dry-run` option to see if it would find the target

**Comment by directionless** [comment]
As a slight counterpoint, I use TUF in the real world, and I have few enough delegations and targets that I find it quite useful to be able to list them all.

**Comment by asraa** [comment]
> that I find it quite useful to be able to list them all.

I would also like to at least keep a command that would list targets, but maybe we can do this on a per-delegation basis?

e.g. `tuf-client list` prints top-level targets
`tuf-client list <delegation>` prints targets for delegation

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client.

There might be a CLI based on this, but it will live in a separate repository.

Thanks for raising this 👍
