### ISSUE TITLE
client: Record fixed update start time

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#217]
Description:

- As per the client workflow described in the go-tuf [spec](https://theupdateframework.github.io/specification/latest/#fix-time), the client should implement the following (currently missing) - 

> Record the time at which the update began as the fixed update start time. Time is fixed at the beginning of the update workflow to allow an application using TUF to effectively pause time, in order to ensure that metadata which has a valid expiration time at the beginning of an update does not fail an expiration check later in the update workflow.

**Comment by trishankatdatadog** [comment]
See https://github.com/trishankatdatadog/tuf-on-a-plane/blob/ee8049a63ea439d72509f6e876eef08fb50c6ab1/src/tuf_on_a_plane/config.py#L45

**Comment by rdimitrov** [comment]
Closing this as fixed by the new code base.
