### ISSUE TITLE
client: Clean-up the use of a database to keep client state

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#219]
Description:
- This is more of an implementation enhancement than an issue, but it makes sense to bring it up as it might be worth to discuss
- The idea is to streamline and even deprecate the database usage throughout the code
- Currently, there are several dedicated databases being managed (i.e. for keeping metadata files and keys) and it's not really necessary to have them for our use case. For example, the client caches a list of targets, which is only for non-delegated targets and likely leads to incorrect state usage. Should just do the delegated targets (DFS) search, per spec
- Such refactoring will help by cleaning the client codebase and will remove unnecessary dependencies too

**Comment by asraa** [comment]
Also: would be nice to expose client state in a readable way (expiraitons/versions of top-level meta?)

**Comment by rdimitrov** [comment]
Closing since the code base changed and is no longer relevant.

Thanks for raising this 👍
