### ISSUE TITLE
Expose delegated targets

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#220]
@asraa [writes](https://github.com/sigstore/cosign/pull/1423/commits/3ed0dbc0b28b5a65f10b88a853115f7c24d61e3c#r803752224)

> I'd like to add a DelegatedTargets or iterator/search to get matching targets in the go-tuf client.

I'm happy to take care of this (let me know if it becomes urgent).

**Comment by ethan-lowman-dd** [comment]
Does PR https://github.com/theupdateframework/go-tuf/pull/209 provide the necessary functionality?

**Comment by znewman01** [comment]
Yes, IIUC this issue would just be making sure there's a good public interface to the code moved around in #209.

**Comment by ethan-lowman-dd** [comment]
https://github.com/theupdateframework/go-tuf/pull/244 should also help with this

**Comment by joshuagl** [comment]
Can we close this issue?
