### ISSUE TITLE
interop tests use deprecated python-tuf code

### ISSUE THREAD

**Issue by jku** [theupdateframework/go-tuf#221]
client/python_interop uses the legacy python-tuf client code (the generate.py script also uses legacy repository_tool). python-tuf has recently removed the legacy code from git, and the next release will not contain it anymore.

Updating to new client should be straight forward: There's an example client that might be what you need (https://github.com/theupdateframework/python-tuf/tree/develop/examples/client_example) -- I admit I did not fully find out what the test does.

Updating generate.py might be a bit more work (in the sense that there is no repository_tool API anymore) but amount of code should not be any worse using the low level Metadata API, see https://github.com/theupdateframework/python-tuf/tree/develop/examples/repo_example/basic_repo.py

python-tuf devs are obviously available for advice.

**Comment by znewman01** [comment]
I can probably take this next week.

**Comment by znewman01** [comment]
Oops, looks like promising this week was overly ambitious, but I  should have time next week (week of Feb 21)

**Comment by znewman01** [comment]
Ahh, okay update here: this got blocked on #232.
