### ISSUE TITLE
ecdsa keyval.public format is hex-encoded DER, should be PEM

### ISSUE THREAD

**Issue by jku** [theupdateframework/go-tuf#223]
It looks like the `ecdsa-sha2-nistp256` keytypes `keyval.public` value is incorrectly the hex encoded raw bytes of the key, instead of PEM. Spec says:

> The ["ecdsa-sha2-nistp256"](https://theupdateframework.github.io/specification/latest/#keytype-ecdsa-sha2-nistp256) format is:
> ```
> {
>   "keytype" : "ecdsa-sha2-nistp256",
>   "scheme" : "ecdsa-sha2-nistp256",
>   "keyval" : {
>     "public" : PUBLIC
>   }
> }
> ```
> **PUBLIC**: PEM format and a string.

I'm looking at e.g the sigstore metadata https://github.com/sigstore/root-signing/blob/main/repository/repository/2.root.json#L36 where the value does not seem to be PEM.

Related:
* Spec issue to clarify key format https://github.com/theupdateframework/specification/issues/201
* python-tuf interop issue: https://github.com/theupdateframework/python-tuf/issues/1859
* maybe this issue is a duplicate of #127 ?

**Comment by asraa** [comment]
I think the big problem was that newlines inside JSON couldn't be handled well with go. I pulled a PEM encoded public key string from python repository testadata and you'll usually get invalid chars trying to unmarshal:
https://go.dev/play/p/WikoJBIBMRo

**Comment by jku** [comment]
I realize the following is not useful to solve the problem that we have now but I'll say this to any future developers thinking of a similar workaround: _Redefining an existing keytype is not the best solution to this problem. The specification supports new keytypes just fine._

I don't have ideas to fix the issue at hand: I'm not very familiar with the go deployment styles but I suppose we are now in a situation where:
* current clients only accept hex ecdsa keys
* even if client code is updated to support both, there is no guarantee that clients are updated
* even if the metadata generating code is fixed, repositories currently serving hex ecdsa keys might not want to switch to PEM keys because of above point

What the project can definitely do is document the issue: _"go-tuf does X in a non-compliant way: it works fine but may prevent using other TUF implementations with the same metadata"_

**Comment by toby-jn** [comment]
Implemented a fix for this in: https://github.com/theupdateframework/go-tuf/pull/270
