### ISSUE TITLE
Rename AddTargetsWithDigest to AddTargetWithDigest, implement missing AddTargetWithDigestWithExpires

### ISSUE THREAD

**Issue by ethan-lowman-dd** [theupdateframework/go-tuf#242]
This will be a breaking change.

The name `AddTargetsWithDigest` breaks the naming convention for `AddTarget*` methods, since only one target is being added. This might be something we can bundle with a refactor of the `AddTarget*` methods to use something like the options pattern, since the current naming is quite verbose.

**Comment by rdimitrov** [comment]
Closing since the code base changed and it is no longer relevant.

Thanks for raising this 👍
