### ISSUE TITLE
Unexpected behavior: passing empty slice of paths to AddTargets* functions adds all staged targets instead of none

### ISSUE THREAD

**Issue by ethan-lowman-dd** [theupdateframework/go-tuf#243]

**Comment by asraa** [comment]
It also seems like this adds all staged targets to the a delegation if we do something like:
`repo.AddTargetsWithExpiresToPreferredRole([]string{}, nil, expiration, delegation-foo)`

for better (bad) compatibility, could we restrict this to when the preferred role is the top-level targets, and not any targets file? (i.e. disclude delegations)

**Comment by rdimitrov** [comment]
Closing since the code base changed and is no longer relevant

Thanks for raising this 👍
