### ISSUE TITLE
Why does "func NewP256Signer()" returns an "ed25519Signer"?

### ISSUE THREAD

**Issue by cedricvanrompay-datadog** [theupdateframework/go-tuf#258]
From https://github.com/theupdateframework/go-tuf/blob/0e889ad1c/pkg/keys/ed25519.go#L18:

```go
func NewP256Signer() Signer {
	return &ed25519Signer{}
}
```

Is this on purpose? Someone calling `NewP256Signer` would probably expect to get a signer using ECDSA over P-256 curve, and not a signer using Ed25519.

**Comment by asraa** [comment]
This is fixed now.

You can generate an ecdsa key with `keys.GenerateEcdsaKey()`
