### ISSUE TITLE
Client local store does not include delegated target roles

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#262]
After a client update, I expect that any trusted delegated role's metadata would exist in the client's [Local Store](https://github.com/theupdateframework/go-tuf/blob/0e889ad1c804fe0aaae895a8642a664f53847e23/client/local_store.go#L13)

I'm not 100% sure when this should happen, but I do think that `client.Update()` should perform a load of the delegated targets (https://github.com/theupdateframework/go-tuf/blob/0e889ad1c804fe0aaae895a8642a664f53847e23/client/client.go#L902), and that function should `SetMeta` when downloading the delegated target file.

Or --  we continue to do a lazy update, and only when all targets are retrieved or certain ones are downloaded do delegated filenames show up.

@mnm678 @ethan-lowman-dd @rdimitrov

**Comment by trishankatdatadog** [comment]
You mean downloading all delegated targets metadata? That would be too expensive in some cases. Lazy evaluation seems better to me.

**Comment by mnm678** [comment]
I agree, the client shouldn't need to download all of them, just the ones needed for any verification they perform.

**Comment by rdimitrov** [comment]
@asraa - Should we close this one? As @mnm678 and @trishankatdatadog said, that might be too costly. I see that python-tuf too doesn't update the whole delegated metadata set upon Update() (or refresh() in the python-tuf case). Instead, it downloads enough delegated metadata to return the target (ref. [python-tuf/updater.py](https://github.com/theupdateframework/python-tuf/blob/3f28d406b58c23b368c5921951bd2ebd6c077557/tuf/ngclient/updater.py#L113))

**Comment by rdimitrov** [comment]
Closing since the code base changed and so this is no longer relevant.

Thanks for raising this 👍
