### ISSUE TITLE
Retain remote version update on error

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#29]
If an update determines a newer version of a file exists, it should retain that information locally even if there is a subsequent error in the update process.

**Comment by trishankatdatadog** [comment]
Not clear whether successfully verified metadata are saved despite failures to verify _subsequent_ metadata later in the same update session, which is what the spec currently requires.

**Comment by rdimitrov** [comment]
I believe we can close this one as this is the way the client workflow is currently implemented. For example, even if the update for snapshot failed, the timestamp meta was already updated/saved locally in order to get to the step of updating the snapshot.
