### ISSUE TITLE
Support delegations in the CLI

### ISSUE THREAD

**Issue by mnm678** [theupdateframework/go-tuf#296]
We added delegation support in #175. Now, it would be great to add support for them to the CLI. I envision something like the following:

* `delegate from_role to_role namespace`
* Add a parameter to `add` for the role that the target is added to
* `remove-delegation from_role to_role`

Feedback would be appreciated, especially on the names

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client.

There might be a CLI based on this, but it will live in a separate repository.

Thanks for raising this 👍
