### ISSUE TITLE
docs: create a docs folder

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#303]
Currently, there's no `docs` folder for the project and it make sense to have one given there are already a few issues related to adding specific guidelines and documentations.

**Comment by ithiel883** [comment]
can i be assigned this issue?

**Comment by znewman01** [comment]
Hi @ithiel883! Thank you for volunteering!

I believe #309 will fix this, so I'm actually going to assign it to myself. 

If you're interested in other good getting-started issues, here are a few. If you're interested, comment there. And if you run into any trouble, comment and we'll try to give some guidance :smile: 

- https://github.com/theupdateframework/go-tuf/issues/307
- https://github.com/theupdateframework/go-tuf/issues/156
