### ISSUE TITLE
code: re-examine the API design of go-tuf

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#304]
This was being raised from time to time through meetings so the purpose of this issue is to serve as a place where we can discuss if, when and how to approach this.

We'll see if this should cover both the API and CLI design provided by go-tuf or we should have separate discussions for each.

**Comment by znewman01** [comment]
Some discussion on this in the [go-tuf maintainer's meeting](https://hackmd.io/dm0C3LpDTHOsQYZfUXRcBw?view):

Focusing on the client (which is the more pressing interface):
- python-tuf did a big redesign, it took a long time (a year)
- however, it wasn't that much coding—mostly design!
- the metadata API is a good idea; most everything else falls out from that
- we could probably do something similar

**Comment by rdimitrov** [comment]
Closing since the code base changed as a result of these discussions.
