### ISSUE TITLE
Contributor licensing

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#308]
#190 adds a DCO requirement. This was somewhat controversial.

We should:

1. Make a decision on contributor licensing.
2. Document and enforce it.

Summary of available options.

# [Developer Certificate of Origin](https://wiki.linuxfoundation.org/dco) (DCO)

Pros:

- It's what python-tuf does.
- Lighter-weight, legally speaking, than a CLA: many developers are able to sign a DCO but *not* a CLA
- Easy to enforce: there's an off-the-shelf GitHub action.

Cons:

- Can be annoying to type `-s` all the time.
- Makes GitHub web UI changes difficult (you can manually add the `Signed-off-by:` line).

# [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement) (CLA)

Pros:

- Set-and-forget: you just have to sign it once.

Cons:

- Some contributors are unable (often due to their employer) or unwilling (due to the legal requirements) to sign a CLA.
- Enforcement is more of a pain. We also have to pick a CLA.

# Do nothing

Pros:

- Status quo; don't have to do anything. Seems to be working so far.
- Other TUF projects seem to be okay with this.
- Nobody has ever convinced me that these things matter.

Cons:

- Legal risks (???)

**Comment by joshuagl** [comment]
DCO is now easier to manage through the GitHub web UI, admins can mark it as required and the UI will fill it in automagically: https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

I should add that python-tuf requires DCO: https://github.com/theupdateframework/python-tuf/blob/develop/docs/CONTRIBUTING.rst#dco

**Comment by mnm678** [comment]
I think DCO is easier for most people. It looks like the cncf wants projects to have [some kind of contributor licence](https://github.com/cncf/foundation/issues/130)

**Comment by trishankatdatadog** [comment]
> Pros:
>
> * Nobody has ever convinced me that these things matter.
> 
> Cons:
> 
> * Legal risks (???)

Exactly. So let's just go with the simplest thing. DCO is fine by me considering recent changes.

**Comment by znewman01** [comment]
It appears that I don't have the permissions to set this up: https://github.com/dcoapp/app#usage

Someone with "write access" to the `go-tuf` repo needs to configure the repo in Settings > Branches > Branch protection for `master` > Require status checks to pass before merging > DCO (check it!).

You may also need to "install" the DCO bot: https://github.com/apps/dco > Configure.

**Comment by rdimitrov** [comment]
@joshuagl - I think you may have the necessary rights 👍

**Comment by joshuagl** [comment]
I've installed the app, but we need a PR to be opened after it has been installed to trigger the check before we can enable the branch protection

**Comment by znewman01** [comment]
> I've installed the app, but we need a PR to be opened after it has been installed to trigger the check before we can enable the branch protection

Does https://github.com/theupdateframework/go-tuf/pull/319 work?

**Comment by joshuagl** [comment]
It does, all set up :-)
