### ISSUE TITLE
Implement `tuf regenerate`

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#31]
I should be able to run `tuf regenerate` to regenerate `targets.json` based on the target files in the committed `targets` directory.

**Comment by mnm678** [comment]
There is a skeleton of this here: https://github.com/theupdateframework/go-tuf/blob/master/cmd/tuf/regenerate.go

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client. 

There might be a CLI based on this, but it will live in a separate repository. 

Thanks for raising this 👍
