### ISSUE TITLE
Tests rely on symlinked files in testdata, which don't work in Windows by default

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#313]
Thanks to @torin-carey for catching this!

>Another problem I've noticed running git on windows locally is that git for windows by default does not create symlinks, causing some of the test cases to fail where test case metadata files are de-duplicated through links. Github workflows seems to enable core.symlinks so this shouldn't be a problem for the CI, but may be for users. Should we remove the symlinks or just leave it as-is?

Good find. I think we can address this later; I'll file an issue. The symlinks are all consistent snapshot-related so I think they're somewhat deliberate.

TBH I'd prefer to keep the symlinks and fix this with documentation. If we *must* remove them, we'd need some automation around making sure the files stay in sync.

_Originally posted by @znewman01 in https://github.com/theupdateframework/go-tuf/issues/274#issuecomment-1151262968_

**Comment by rdimitrov** [comment]
Closing since the code base changed and we are no longer using the same tests.

Thanks for raising this 👍
