### ISSUE TITLE
docs: update the CLI usage documentation

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#322]
The documentation about the usage of both repository and client side CLIs should be refreshed so it matches the current features which `go-tuf` provides. 

The things that need to be fixed are the following (nevertheless it won't hurt if we have a look at the rest too):

- `tuf-client init` does not work with root keys anymore, but instead uses the `root.json` file as per the spec (Thanks to Alex Khanin for raising that in #tuf (CNCF Slack channel)). 
- In the same context, `tuf root-keys` command is obsolete too. 
- `tuf regenerate` is not implemented yet, so maybe we can remove it if it's something we don't need or plan for the time being?

**Note:**
Removing the `root-keys` command might also be followed by removing the `init` implementation we kept as being backwards compatible. For reference - https://github.com/theupdateframework/go-tuf/pull/210 and https://github.com/theupdateframework/go-tuf/issues/208

**Comment by keerthi-nallaginela** [comment]
Hi, Can I take this up?

**Comment by rdimitrov** [comment]
@keerthi-nallaginela - Of course! Let us know if there is anything we can help you with 👍

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
