### ISSUE TITLE
Double-check  go-securesystemslib optimizations

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#326]
CC @adityasaky 

https://github.com/secure-systems-lab/go-securesystemslib/pull/25 makes some changes to the canonical format encoder. They *shouldn't* break go-tuf.

That PR was merged in a branch, so we need to double-check explicitly.

**Comment by mnm678** [comment]
I ran the go-tuf tests using the `go-securesystemslib` branch locally and everything passed. I think we are safe to close this issue.
