### ISSUE TITLE
Delegations: Unable to modify properties of a delegated role 

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#330]
If a user adds a delegation with a repeated name, but with different properties (e.g. Updates it), then it will catch on this error:

https://github.com/theupdateframework/go-tuf/blob/355e39cb2df220fc3961396a6d0e30bcf2c9ac12/repo.go#L559-L563

@ethan-lowman-dd WDYT?

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
