### ISSUE TITLE
Document release instructions

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#335]
CC @asraa who was interested in having another minor release version cut.

I realized that I don't actually know how to cut a release (or whether I have the appropriate permissions).

@rdimitrov , I think you cut the last one---if you try to outline the instructions quickly in this issue, I can go through them to troubleshoot, and then I'll add the instructions to `docs/MAINTAINERS.md`.

**Comment by joshuagl** [comment]
AFAIK everything should happen automatically when a tag matching the format `v*` is pushed. Pushing the tag triggers the CI workflow, which in turn triggers the release workflow.

**Comment by znewman01** [comment]
Oh, excellent.

That leaves two questions:

1. Who has/should have the privileges to push a tag?
2. What is the process for deciding to cut a release?

**Comment by joshuagl** [comment]
Anyone with write access to the repository can push tags at present. We might want to set up [protected tags](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) in future, though.

I don't think we have a formal process for when to cut a release today. There's a project board building to the next release, but I'm OK with inserting a release sooner. Especially as @asraa needs one.

Let's go ahead and make a release.

**Comment by znewman01** [comment]
Great! I pushed `v0.3.1`: https://github.com/theupdateframework/go-tuf/tree/v0.3.1

I will keep an eye on it, and document something reflecting this process before resolving this issue.
