### ISSUE TITLE
update leveldb with fsync fix

### ISSUE THREAD

**Issue by mfmarche** [theupdateframework/go-tuf#349]
See: https://github.com/syndtr/goleveldb/issues/335

" leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000006] "

We have seen this issue where a reboot/crash of the tuf client causes the leveldb to be corrupted. Updating the goleveldb version to the latest suggests it will fix this.

**Comment by joshuagl** [comment]
I wonder why dependabot hasn't picked this up 🤔

**Comment by mfmarche** [comment]
I believe the leveldb library didn't publish a version/tag, which is likely the reason; I had to use a hash.
