### ISSUE TITLE
Should SignMessage guard against large metadata?

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#358]
It's not likely to be a large metadata file, but should we watch out for it?

_Originally posted by @trishankatdatadog in https://github.com/theupdateframework/go-tuf/pull/357#discussion_r949673578_

See here: https://github.com/theupdateframework/go-tuf/blob/4febe4c81aa17b39a87c1bab1c6592b347ff4a56/pkg/keys/keys.go#L57

`SignMessge` takes in an arbitrary length message bytes and hashes it before signing. In my opinion, sining is never done by the client so it's not as much of a threat. 

On the other hand, the general procedure of unmarshalling metadata should come with JSON size limits. Client fetchers may already do this.

**Comment by znewman01** [comment]
👎 to adding length limits to `SignMessage`, you shouldn't be signing things you haven't validated or created yourself anyway

👍 to making `SignMessage` take in an `io.Reader` (which would enable using a [`LimitedReader`](https://pkg.go.dev/io#LimitedReader) if a caller cares)

> On the other hand, the general procedure of unmarshalling metadata should come with JSON size limits. Client fetchers may already do this.

python-tuf [has these limits](https://github.com/theupdateframework/python-tuf/blob/367b75f39689fdf5881ee7a3815064d125e2185b/tuf/ngclient/config.py#L31-L34). It enforces them at fetch-time (e.g., [for root](https://github.com/theupdateframework/python-tuf/blob/367b75f39689fdf5881ee7a3815064d125e2185b/tuf/ngclient/updater.py#L312-L316)). I think that makes way more sense than doing it at `SignMessage` time.

**Comment by trishankatdatadog** [comment]
> 👎 to adding length limits to `SignMessage`, you shouldn't be signing things you haven't validated or created yourself anyway
> 
> 👍 to making `SignMessage` take in an `io.Reader` (which would enable using a [`LimitedReader`](https://pkg.go.dev/io#LimitedReader) if a caller cares)

I don't feel strongly either way, but defence-in-depth is always a good idea.

>> > On the other hand, the general procedure of unmarshalling metadata should come with JSON size limits. Client fetchers may already do this.
> 
> python-tuf [has these limits](https://github.com/theupdateframework/python-tuf/blob/367b75f39689fdf5881ee7a3815064d125e2185b/tuf/ngclient/config.py#L31-L34). It enforces them at fetch-time (e.g., [for root](https://github.com/theupdateframework/python-tuf/blob/367b75f39689fdf5881ee7a3815064d125e2185b/tuf/ngclient/updater.py#L312-L316)). I think that makes way more sense than doing it at `SignMessage` time.

Agree, this is where it's more important: during verify, not signing.

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid. Similar to python-tuf we do verify the length of the metadata when loading one.

Thanks for raising this 👍
