### ISSUE TITLE
Add support for verifying file and directory permission on Windows

### ISSUE THREAD

**Issue by kommendorkapten** [theupdateframework/go-tuf#360]
Initially discussed in this PR https://github.com/theupdateframework/go-tuf/pull/347, see this comment https://github.com/theupdateframework/go-tuf/pull/347#issuecomment-1211615181 for more details.

That PR adds support for verifying that the permission mode for the metadata cache is a bit more restrictive, the "others" group can not read nor write any of the files, but it does not work on Windows. 
Just a note, this functionality is not required by the TUF spec, but it is a nice to have feature.

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid. Do reopen if needed 👍 

Thanks for raising this 👍
