### ISSUE TITLE
Fix: Handle errors in Key interface

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#363]
The key interface does not support error handling on the following points:
`MarshalPublicKey()`, `Public()`, `PublicData()`

https://github.com/theupdateframework/go-tuf/blob/ebbc6b8d12d861335a3fc6e7fd8c69a53acaa1e6/pkg/keys/keys.go#L33

In case someone creates a key without unmarshalling first, we should handle these errors.

**Comment by dibrinsofor** [comment]
can I take this up? @asraa 

Just to confirm, we just want to ensure that keys are unmarshalled before they are returned?

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
