### ISSUE TITLE
Remove `keyid_hash_algorithms`

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#368]
`go-tuf` added `keyid_hash_algorithms` as a field in [2fbbd60](https://github.com/theupdateframework/go-tuf/commit/2fbbd60ee12ffeb9f2bceeefb5896f9f52eadaef) (June 2020); see [python-tuf#848](https://github.com/theupdateframework/python-tuf/issues/848) for context. However, it never made it into the spec, and now it’s not needed due to [TAP-12](https://github.com/theupdateframework/taps/blob/master/tap12.md) (which is accepted). python-tuf removed it ([python-tuf#1014](https://github.com/theupdateframework/python-tuf/pull/1014)); we should too.

**Comment by znewman01** [comment]
@trishankatdatadog brings up a good point: be careful about backwards compat here! Old clients may expect this field.

So we should:

- stop expecting it (client side) immediately
- after a minor version bump, stop producing it (repo side) for new repos
- have an option to keep producing it indefinitely, if a repo ever had it (they probably don't want to break old clients)

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is already fixed.

Thanks for raising this 👍
