### ISSUE TITLE
Create security policy

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#371]
e.g. [SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)

Worth modifying the issue/PR templates too.

Motivation: https://github.com/theupdateframework/go-tuf/pull/369 (which was fine! it didn't violate any guidelines because go-tuf had none 😄)

**Comment by znewman01** [comment]
Make sure to compare with other TUF-ecosystem policies.

**Comment by joshuagl** [comment]
AFAIK GitHub doesn't have any tooling to support a private reporting mechanism for maintainers, any thoughts on a good approach for this? Managing a mailing list feels like too much, do we list maintainer email addresses and GPG keys in SECURITY.md?

**Comment by mnm678** [comment]
> AFAIK GitHub doesn't have any tooling to support a private reporting mechanism for maintainers, any thoughts on a good approach for this? Managing a mailing list feels like too much, do we list maintainer email addresses and GPG keys in SECURITY.md?

emails and GPG keys is the approach used by [other TUF implementations](https://github.com/theupdateframework/python-tuf). It's not the easiest to use, but seems like the best option.

**Comment by trishankatdatadog** [comment]
How about a [Google Form](https://buttondown.email/cryptography-dispatches/archive/cryptography-dispatches-replace-pgp-with-an-https/)? Seems like the biggest bang for the buck.

**Comment by trishankatdatadog** [comment]
An example from [Uptane](https://github.com/uptane/uptane-standard/pull/231/files)

**Comment by trishankatdatadog** [comment]
Example policy from [tough](https://github.com/awslabs/tough/security/policy)

**Comment by trishankatdatadog** [comment]
Can probably use [this](https://securitytxt.org/) template

**Comment by znewman01** [comment]
> Can probably use [this](https://securitytxt.org/) template

That seems a little circular: it asks for a link to a security policy 😛 

The OpenSSF has a guide to choosing a disclosure policy here that might be useful: https://github.com/ossf/oss-vulnerability-guide

**Comment by asraa** [comment]
AIs:
- [ ] Create a Google Form submission form with direct maintainer emails (MUST)
- [ ] Create a SECURITY.md (MUST)
- [ ] Move to a mailing list with perms (COULD)
- [ ] Create a small job or a placeholder to revisit the members of that mailing list (COULD)
