### ISSUE TITLE
go-tuf logs to stdout/stderr when used as a library

### ISSUE THREAD

**Issue by tamird** [theupdateframework/go-tuf#376]
Internal operations log directly to stdout/stderr starting with #160.

It would be preferable not to interact with stdout/stderr except from within cmd/.

**Comment by asraa** [comment]
I agree! We get logging from libraries. Repo commands can be logged directly from the cmd/.

We can make sure there is no logging done in `repo.go` or `pkg/`

What about our deprecated code? I think it's ok to remove the logging that you are using a deprecated key, since libraries will obviously import them proactively.

**Comment by joshuagl** [comment]
Thanks for filing this, and for the suggestion in https://github.com/theupdateframework/go-tuf/pull/160#issuecomment-1241063478

> Would it be possible to thread an `io.Writer` through rather than calling `fmt.Print{f,ln}` directly?

That's a good suggestion. I think we want to:
* switch from `fmt.Print{f,ln}` to `log.Print{f,ln}`
* take an optional `io.Writer` in library code (notably repo.go) so the caller can choose where the logging messages go

**Comment by asraa** [comment]
I'm going to prioritize this and take this on: `cosign` users are complaining :)

**Comment by asraa** [comment]
So currently I'm piping an optional logger through the client.

I would like to only log the tuf ecdsa deprecated message once per client. that would maybe require a singleton in the client for that message? that feels sorta messy. anyone have any other nice go suggestions?

**Comment by trishankatdatadog** [comment]
> anyone have any other nice go suggestions?

@ethan-lowman-dd wdyt?

**Comment by asraa** [comment]
It could be that we don't care at all for repeated lines now that we can divert the logs to a file!
