### ISSUE TITLE
AddOrUpdateSignature does not handle root signatures from revoked keys

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#377]
**Description**

[AddOrUpdateSignature](https://github.com/theupdateframework/go-tuf/blob/61872a3ac6e6a475771c23bf1592a00c1773b3e7/repo.go#L793) does not handle adding signatures for keys that were revoked. This case needs to be handled so that the previous root keys can achieve a threshold number of signatures on the current root.

Thinking about how to implement this.
Currently, we create a DB of valid key IDs to check against before adding the provided signature.

Question:
1. Should we ignore the case for root?
2. Should we check the local store for a previous root? This would be a bit of complicated code.
3. Do we allow any key ID's signature into the envelope, regardless of whether it's a key in the DB? It's up to clients to verify that the key ID is trusted FWIW. Does TUF spec call this out? (can anyone endorse the content of a metadata file?)

**Comment by trishankatdatadog** [comment]
Yes, that behaviour does seem a bit overzealous, even if well-intentioned. My recommendation would be to add a new function that does not follow this "safe" behaviour, and refactor common logic between the old and new functions. WDYT?

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
