### ISSUE TITLE
Add support for searching through delegations more easily

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#378]
The only way to search for a target in a delegation is by knowing for the target name ahead of time through `client.GetTarget(name string)`.

If I want to perform a delegation search with the iterator to, let's say, find targets signed by a certain delegation name, or by finding targets that look like `some/target/dir`, or simply return all target names signed by the repository, I have to re-implement the code in [getTargetFileMeta]. However, `c.loadDelegatedTargets` is a private method, and is required to verifiably get the delegated targets file.

Question: TUF specification only describes "Fetching a desired target". How can I discover what targets the repository signs off on though?

Can we make the logic for a delegations iterator more general, and have a general client function for searching a repository targets based on some property? (e.g. match on target wild-card name, match on delegation name, match on delegatee name). 

I admit I'm not sure on the best API for this. Maybe the answer is to make the iterator take in the client that can perform the validation logic internally, and users can use the iterator to do whatever they want.

**Comment by asraa** [comment]
cc @kommendorkapten @joshuagl for sigstore.

Right now, all we ever get from `client.Targets()` is the top-level metadata. We can search for `client.GetTarget('rekor/rekor/rekor.0.pub`)` but we don't know these apriori. Essentially right now all we're getting functionally is top-level targets.

**Comment by trishankatdatadog** [comment]
@asraa Would you please describe a few concrete queries here, so we can see how to implement this? Thanks!

**Comment by kommendorkapten** [comment]
What I imagine is something like this.
The targets directory for this example:
```shell
$ find targets -type f
targets/rekor/key1.pub
targets/rekor/key2.pub
targets/rekor/foo
targets/another_delegate/bar
```

Adding a new function 
```go
type Filter func(t target) bool
FilterAll := func(t target) {return true}
func AllTargets(f Filter) []targets {
    // Perform a recursive search over all targets, including any targets defined by delegates, 
    // applying the filter for each target.
    return response
}
```

Then we could as an example define a filter for rekor:
```go
func RekorOnly(t target) bool {
    return strings.HasPrefix(t.Path, "rekor/")
}
```
One could imagine a filter RekorKeys too, matching the path against `rekor/*.pub`. 

Example queries could be:
`client.AllTargets(RekorOnly)`:
`[{target: rekor/key1.pub}, {target: rekor/key2.pub}, {target: rekor/foo}]`

`client.AllTargets(FilterAll)`:
`[{target: rekor/key1.pub}, {target: rekor/key2.pub}, {target: rekor/foo}, {target: another_delegate/bar}]`

etc etc.

@asraa is this related to what you had in mind?

**Comment by joshuagl** [comment]
> Question: TUF specification only describes "Fetching a desired target". How can I discover what targets the repository signs off on though?

TUF is designed under the assumption that it will be integrated into an existing system (where in more complex cases index/querying is already handled) and that we know what we are trying to retrieve securely with TUF ahead of time.

The semantics of delegations, especially hashed bin delegations, make query effectively impossible to provide in a TUF library API. How delegations are made (and what they mean) is application specific and forms part of the contract between the repository and the client.

Therefore, I don't think we can provide API for this in go-tuf. Hopefully we _can_ provide API in go-tuf to make the application developer's life easier.

**Comment by joshuagl** [comment]
See also very relevant discussion in python-tuf https://github.com/theupdateframework/python-tuf/issues/1995

**Comment by kommendorkapten** [comment]
> TUF is designed under the assumption that it will be integrated into an existing system (where in more complex cases index/querying is already handled) and that we know what we are trying to retrieve securely with TUF ahead of time.

This is a very good comment, as I think this was something I didn't really grasp during Sigstore TUF v2 client discussions. Or maybe I had an idea that the Sigstore client was the "existing system". Have to revisit this and think more when I get time.

**Comment by jku** [comment]
Copying my latest comment from the python-tuf issue:

> I guess I should update current thinking on this.
> 
> I think exposing the metadata to clients as described has security implications that may mean this is not a good idea. The fact that a delegated roles metadata contains targetpaths does not mean that those targetpaths have been delegated to the role. So exposing the list as is seems wrong, even if this is documented as unsafe.
> 
> The only really safe way to do this would be to, after choosing the role, to run the delegation lookup for each targetpath, and only expose the target to client if the targetpath really is delegated by the role in question. This sounds a bit wasteful but in practice might work just fine: in usual cases this would not lead to new metadata downloads and all required metadata would already be loaded in memory.

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid. 

Thanks for raising this 👍

**Comment by eikenb** [comment]
> Closing since the code base changed and this is no longer valid.

Sorry for the zombie comment but I'm wondering what changed in the code base to make this no longer valid? There still doesn't seem to be a way to retrieve the Delegates metadata without first running GetTargetInfo().

**Comment by kommendorkapten** [comment]
It's closed as "won't fix". See Josuha's comment https://github.com/theupdateframework/go-tuf/issues/378#issuecomment-1254863760 for more details.

**Comment by eikenb** [comment]
In case others come across this thread while looking into the same issue our workaround was to include a hardcoded, dummy target in each delegate role. Then we can query that target and it will load up the information from that delegate role including all the other targets it handles.

**Comment by jku** [comment]
> In case others come across this thread while looking into the same issue our workaround was to include a hardcoded, dummy target in each delegate role. Then we can query that target and it will load up the information from that delegate role including all the other targets it handles.

Please make sure you have you read the discussion (like [comment](https://github.com/theupdateframework/go-tuf/issues/378#issuecomment-1335200498) above ) WRT how this potentially sidesteps some of the security guarantees delegation is supposed to give you. Some use cases may be ok but using TUF metadata for artifact discovery has some weird corner cases.
