### ISSUE TITLE
Release notes don't display breaking changes obviously

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#382]
https://github.com/theupdateframework/go-tuf/pull/354 is marked as breaking:

- `refactor!` with a `!` in the conventional commit
- "breaking" box ticked in the PR
- "BREAKING CHANGE" in the PR description

However, it's in the [0.4.0](https://github.com/theupdateframework/go-tuf/releases/tag/v0.4.0) release, which doesn't call it out specifically. Should it?

(Or did I do something wrong?)

**Comment by rdimitrov** [comment]
Goreleaser uses a regex against the **PR title** to match if upon merge it should be added to a given group (i.e. the "Breaking changes" group). 

So far we look for the following prefix - https://github.com/theupdateframework/go-tuf/blob/06ed59941769f55b7d54158a0be85a16a7475fa7/.goreleaser/tuf.yml#L26, but we can totally switch to something else 👍  

Ticking the box and/or adding additional info in the description is useful to inform others and to highlight to the maintainers to make sure the title includes the necessary prefix so it gets handled properly in the release notes. It would be nice if there's a way to automate that in some way, i.e. ticking a box to alter the PR title, but I'm not aware of anything like that.

In any case, this part is missing from the docs, so I'll push an update to our guidelines 😃

**Comment by znewman01** [comment]
Gotcha. I would like to honor the `!` convention from conventional commits, so let's change that regex. I can make a PR.

**Comment by znewman01** [comment]
FWIW the "BREAKING CHANGE" convention in convention commits isn't supposed to go in the PR title, it's supposed to be a footer. So I think looking for `BREAKING CHANGE` in the title in the regex is wrong, though probably not worth fixing.
