### ISSUE TITLE
Client update doesn't fix a start time

### ISSUE THREAD

**Issue by znewman01** [theupdateframework/go-tuf#386]
[Section 5.1 of TUF v1.0.30](https://theupdateframework.github.io/specification/v1.0.30/index.html#fix-time) (current latest release):

>  Record fixed update start time
>
> Record the time at which the update began as the fixed update start time. Time is fixed at the beginning of the update workflow to allow an application using TUF to effectively pause time, in order to ensure that metadata which has a valid expiration time at the beginning of an update does not fail an expiration check later in the update workflow.

We don't do that. Expiration is checked in verify/verify.go:

https://github.com/theupdateframework/go-tuf/blob/master/verify/verify.go#L69-L71

Which always uses the current time.

**Comment by trishankatdatadog** [comment]
Good observation. I also recommend a "[slack time](https://github.com/trishankatdatadog/tuf-on-a-plane/blob/ee8049a63ea439d72509f6e876eef08fb50c6ab1/src/tuf_on_a_plane/config.py#L45)" to be forgiving when necessary.

**Comment by znewman01** [comment]
Dupe of https://github.com/theupdateframework/go-tuf/issues/217
