### ISSUE TITLE
Command to remove a key

### ISSUE THREAD

**Issue by mnm678** [theupdateframework/go-tuf#388]
`revoke-key` revokes a key, but leaves it in the `keys/` directory. It would be nice to have a separate command that removed the key, something like `tuf remove-key role keyid`.

**Comment by rabajaj0509** [comment]
I would like to work on this issue.

**Comment by rdimitrov** [comment]
Thanks, @rabajaj0509. Feel free to reach out here in case you have any questions 👍

**Comment by rdimitrov** [comment]
cc: @JuliannaReyes

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client.

There might be a CLI based on this, but it will live in a separate repository.

Thanks for raising this 👍
