### ISSUE TITLE
RemoveTargetsWithExpires does not pin to a preferred delegation

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#400]
`repo.RemoveTargetsWithExpires` will remove a target from ALL delegated target metadata: there is no way to specify a certain targets or delegation role.

This means that if a delegation had signed off on the same path as another (allowed), or one of top-level that takes precedence, then removing the target in the delegaiton (intended) will remove it everywhere.

cc @joshuagl detected this in sigstore root-signing
https://github.com/sigstore/root-signing/pull/410

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
