### ISSUE TITLE
Enable all FileStore tests on Windows

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/go-tuf#407]
One of the tests in file_store_tests.go:TestCreates is disabled only for Windows hosts:

https://github.com/theupdateframework/go-tuf/blob/3890c1e7ace43d67622428187a85ba486c2528e5/client/file_store_test.go#L26-L33

This test was introduced in PR #397 and disabled for Windows because we could not root cause why it was failing on that OS in CI.

We should fix the test and undo the change to disable it: https://github.com/theupdateframework/go-tuf/pull/397/commits/dabde9fabcd2983ecfca5fbf2e0202e52e62dd75

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
