### ISSUE TITLE
List signing keys

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#41]
I should be able to list the IDs of the current signing keys and whether they are present locally, for example:

```
$ tuf list-keys
ROLE       KEYID                                                             LOCAL
root       8fb16df0010dfeeb5737245e527e598fdf38cf92aea18a205e19fbf97c5766fd  false
snapshot   5a83cb8e2db2dceada45b14c6ab36c44618b26518b7fc9800f737cc54de9ffe2  true
targets    6ee7468ea4027e8c813ed774f2959336e6fb0c7015a0df73fbe3b24aa76a34a2  false
targets    a418bc9ec8699df5903779fe2c80058ac0ba2843b956e535aa377a6c99c56499  true
timestamp  6a14c18be9ea8e3b53509e0644e79097f933303186bd649ef199f854c5f0a86d  true
```

**Comment by mnm678** [comment]
Not sure how to determine if a key is present locally.

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client. 

There might be a CLI based on this, but it will live in a separate repository. 

Thanks for raising this 👍
