### ISSUE TITLE
Properly deprecate custom metadata in snapshot file metadata

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#411]
https://github.com/theupdateframework/go-tuf/pull/373

See context.

This is out of TUF specification, and the user should actually put this information in the parent role's DELEGATIONS object.

As with @trishankatdatadog, this field is not in the TUF specification: https://theupdateframework.github.io/specification/latest/#file-formats-snapshot

If you want to keep information about a delegated target, then ideally the information should live in/signed by the parent role, rather than the snapshot role, correct?

It seems like you may want CUSTOM metadata inside a DELEGATIONS object long-term, right? https://theupdateframework.github.io/specification/latest/#delegations

@arbll

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is no longer valid.

Thanks for raising this 👍
