### ISSUE TITLE
API for loading and managing keys from files

### ISSUE THREAD

**Issue by adityasaky** [theupdateframework/go-tuf#427]
go-tuf doesn't currently provide an API to load existing keys from files. It'd be great to be able to load keys from files into their `data.PrivateKey` or `data.PublicKey` representations.

**Comment by udf2457** [comment]
Yes, for people who use PKCS#11 (e.g. Yubikey) or cloud HSM (e.g AWS KSM or Azure KV) it would be very useful to be able to:

1. Load pubkey representations (i.e. provide pem file and it gets parsed into the correct format)
2. Load external signatures (I.e. provide hex string which gets parsed into correct format)

**Comment by asraa** [comment]
+1, we currently handwrite the data.PublicKey conversions for the HSMs we use.

I agree that loading a PEM file or other pubkey representaitons into a public key would be great to start.

**Comment by udf2457** [comment]
For signatures, a good reference point would be to support the `--signature-format` output options from [pkcs11-tool](https://manpages.debian.org/testing/opensc/pkcs11-tool.1.en.html) seeing as `pkcs11-tool` is a widely used reference implemenation:

> --signature-format format
Format for ECDSA signature: 'rs' (default), 'sequence', 'openssl'.

**Comment by rdimitrov** [comment]
Closing since the code base changed and this is now fixed.

Thanks for raising this 👍
