### ISSUE TITLE
Bug: Fix CI permissions 

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/go-tuf#436]
The default permissions of the GITHUB_TOKEN during GitHub Actions were changed this week for the whole organization. 

In our case, Goreleaser depends on having `write` permissions if we want to publish releases to GitHub, so this affects our CI. To solve that we have to elevate the token permissions for the CI workflow.

Reference: 

[Invalid workflow file: .github/workflows/ci.yml#L12](https://github.com/theupdateframework/go-tuf/actions/runs/3603840027/workflow)
The workflow is not valid. .github/workflows/ci.yml (Line: 12, Col: 3): Error calling workflow 'theupdateframework/go-tuf/.github/workflows/release.yml@c803c816c7061506db0791cc128ccf64d24e6226'. The nested job 'release' is requesting 'contents: write', but is only allowed 'contents: read'.

**Comment by trishankatdatadog** [comment]
> In our case, Goreleaser depends on having `write` permissions if we want to publish releases to GitHub, so this affects our CI. To solve that we have to elevate the token permissions for the CI workflow.

Is it possible to override per repo?

**Comment by joshuagl** [comment]
You can just elevate permissions for the job that makes the release, i.e. https://github.com/theupdateframework/python-tuf/blob/7c756efe0084f20eb9de88665e9b299eb8a3d6b2/.github/workflows/cd.yml#L49
