### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by titanous** [theupdateframework/go-tuf#44]
We should have support for target role delegation.

**Comment by ethan-lowman-dd** [comment]
Support has been added for delegation in the client in https://github.com/theupdateframework/go-tuf/issues/44. We still need to add support in the repo writer packages. We (@trishankatdatadog and co. @ Datadog) intend to take on this work.

**Comment by ethan-lowman-dd** [comment]
The repository APIs support delegation as of https://github.com/theupdateframework/go-tuf/releases/tag/v0.2.0
