### ISSUE TITLE
Would it be possible to cut a release 0.5.2?

### ISSUE THREAD

**Issue by vaikas** [theupdateframework/go-tuf#449]
Hey there,

Both cosign and policy-controller in Sigstore currently are using a non-cut release to pick up the airgap verification capabilities that was added in #397 

Before we cut new releases for those, it would be much better to point to a release here. So, asking if it would be possible to get a new release cut, or when the next planned release is? Last one 0.5.1 was in September.

**Comment by asraa** [comment]
@trishankatdatadog @mnm678 @rdimitrov @znewman01 

Only thing that was Must Have on our project is some added testing. I think we can get a release out, honestly. The testing shouldn't take too long, I'll take a look this afternoon. https://github.com/theupdateframework/go-tuf/issues/286

**Comment by trishankatdatadog** [comment]
> @trishankatdatadog @mnm678 @rdimitrov @znewman01
> 
> Only thing that was Must Have on our project is some added testing. I think we can get a release out, honestly. The testing shouldn't take too long, I'll take a look this afternoon. #286

Sounds good. Let me know, and I'm happy to help cut a release.

**Comment by znewman01** [comment]
Thanks @asraa !

I'm supportive of a release. If #286 is going to take longer than a couple days I'd be happy to just push it to 0.5.3.

**Comment by znewman01** [comment]
#450 is merged, I am going to cut a release now

**Comment by znewman01** [comment]
Tag created: https://github.com/theupdateframework/go-tuf/releases/tag/v0.5.2

**Comment by znewman01** [comment]
https://github.com/theupdateframework/go-tuf/releases/tag/v0.5.2
