### ISSUE TITLE
Hashed bins

### ISSUE THREAD

**Issue by titanous** [theupdateframework/go-tuf#45]
We should have support for [hashed bins](https://github.com/theupdateframework/tuf/tree/develop/tuf#delegate-to-hashed-bins).

**Comment by that1boy** [comment]
Hey, @mnm678
I would love to work on this ! Came to know about it from GSoc 21 Ideas.
Could you guide me on this .

**Comment by mnm678** [comment]
Hi! There's a description of this feature in the [specification](https://theupdateframework.github.io/specification/latest/#path_hash_prefixes), as well as in the [python version](https://github.com/theupdateframework/tuf/tree/develop/tuf/client).

**Comment by rdimitrov** [comment]
@mnm678 - Hey, I believe this can be closed via https://github.com/theupdateframework/go-tuf/pull/192, right?

**Comment by mnm678** [comment]
Yes, closing as fixed in #192
