### ISSUE TITLE
docs: Examples needed for client package

### ISSUE THREAD

**Issue by udf2457** [theupdateframework/go-tuf#462]
Currently examples are only available for the CLI client.

Anyone (like me !!) who is trying go get started with the client package in Go app has really no idea where to start.

It would be nice to have a concrete example as to how the client package is supposed to be used.

**Comment by abs007** [comment]
Hi, I was wondering if I could have a go at this, thanks.

**Comment by rdimitrov** [comment]
Hey, @abs007, that would be much appreciated! 💯 

If I can advise you though to only keep in mind that at some point we may have to update these docs so they take into account the [metadata API](https://github.com/rdimitrov/go-tuf-metadata). Keeping it structured would be helpful so if we go that route we'll end up updating only the code portions of this content. Feel free to reach out if you need something 👍

**Comment by abs007** [comment]
@rdimitrov  Is `tuf` different from `tuf-client` (both CLIs) in the way that the earlier is supposed to be used by the repository to set up the metatdata and roles whereas the latter is to be used by the client to manage downloaded metadata?

Also, how does the client package play a role in this? Is it present to be used as part of a program as compared to using the `tuf-client` as a CLI?

**Comment by rdimitrov** [comment]
You're exactly right 👍 Both `tuf` and `tuf-client` are standalone CLIs that are aiming to help in managing respectively the repository side and the client side of a TUF repository. The `client` package on the other hand is a package/library that is intended to be used as a building block for developing other applications.

**Comment by abs007** [comment]
Functions like `getLocalMeta()`, `getDelegationPathFromRaw()` are not present in the [Client package docs](https://pkg.go.dev/github.com/theupdateframework/go-tuf/client#Client). Is there a reason for that?

**Comment by rdimitrov** [comment]
Closing since the code base changed and we already have quite a few examples of how to create a client using the new code base.

Thanks for raising this 👍
