### ISSUE TITLE
Prevent slow retrieval attacks

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#48]
Slow retrieval attacks should be prevented by requiring that remote data is fetched in a timely manner.

The Python implementation guards against this attack by reading remote data in small chunks, and signalling an error if reading any given chunk takes longer than a specified time (see [here](https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L265-L319)).

**Comment by lmars** [comment]
This is largely implemented in [this commit](https://github.com/flynn/go-tuf/commit/8ec663b3a44888d47728dfc4fe094a192b491ca0) (which is on the `prevent-slow-retrieval-attacks` branch).

However, the implemented `timeoutReader` has the side effect that if the given `[]byte` is larger than `chunkSize` and the underlying reader returns partial data, those partial reads will be buffered until enough chunks have been read.

This may not be an issue, but it needs some thought, and probably needs testing against a real (and slow) HTTP server.

**Comment by titanous** [comment]
It looks like `net/http`'s `Request.Body.Close()` is actually dangerous here: golang/go#9662

**Comment by mnm678** [comment]
Slow retrieval attacks were removed from the TUF spec.
