### ISSUE TITLE
Please clarify Copyright holder

### ISSUE THREAD

**Issue by siretart** [theupdateframework/go-tuf#516]
According to the LICENSE file in https://github.com/theupdateframework/go-tuf/blob/5ed62397581b953bacae5bf46b8c7dac4d85df1d/LICENSE#L1

the work is copyrighted by "Prime Directive, Inc".

Is this accurate or should the copyright owners by represented differently?

**Comment by siretart** [comment]
The only other file with copyright statements is


https://github.com/theupdateframework/go-tuf/blob/5ed62397581b953bacae5bf46b8c7dac4d85df1d/client/python_interop/testdata/python-tuf-v2.0.0/client.py#L3-L4

This statement seems to be more in line with what's written at the bottom of https://theupdateframework.io/ ? -- thank you for your clarifications!

**Comment by mnm678** [comment]
That last license file was changed upstream: https://github.com/theupdateframework/python-tuf/commit/f5d08bb0e8a4089fcd976408eca8e05d7c1888e5, and we should probably replace all the license info within testdata to point to the original source to make sure it stays up-to-date (as I believe those are licenses for the underlying python-tuf code).

I think we just want Apache/MIT for this project, but I'm not sure what the process is to change that. @JustinCappos might have more context.

**Comment by JustinCappos** [comment]
It should be replaced.  We had a very small amount of Thandy code in the
very beginning for compat / testing and have had none for essentially the
past 10 years.  Certainly, it is all out after the rewrite / refactor by
our industry friends.  This can be removed everywhere.

**Comment by rdimitrov** [comment]
Closing since the code base changed and the license is now Apache 2 and is consistent across the whole project.

Thanks for raising this 👍
