### ISSUE TITLE
Set expiry on Root and Targets explicitly

### ISSUE THREAD

**Issue by ChevronTango** [theupdateframework/go-tuf#530]
It would be useful to be able to generate a root.json and targets.json, and at a later date change the expiry. Right now you can set the expiry of the snapshots and timestamps, and the targets can have an expiry specified when adding a new target, but you can't alter an existing file in place.

An example for setting the expiry a year from now

```console
tuf expire root.json 364 # A year from now

tuf expire root.json "2024‐07‐30T11:42:01Z" # Explicit time
```

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client.

There might be a CLI based on this, but it will live in a separate repository.

Thanks for raising this 👍
