### ISSUE TITLE
Example repo is dead

### ISSUE THREAD

**Issue by udf2457** [theupdateframework/go-tuf#608]
The example repo(https://jku.github.io/tuf-demo) shown [in the docs ](https://github.com/theupdateframework/go-tuf/tree/master/examples#readme) appears to be dead (404).

Perhaps going forward there's a way for `go-tuf` to host its own instead of relying on a third-party ?  Or maybe convince whoever it is that needs convincing that https://theupdateframework.com/ should host a demo repo somewhere under that URL ?

**Comment by rdimitrov** [comment]
It's actually not dead - https://github.com/jku/tuf-demo?tab=readme-ov-file#using-the-repository-with-a-tuf-client

@jku is the "owner" so far so it's not exactly third party and it's more of a community one that all are welcome to use 👍 I agree that perhaps it might make sense to "donate" it to the TUF org?
