### ISSUE TITLE
Custom user agent string

### ISSUE THREAD

**Issue by kommendorkapten** [theupdateframework/go-tuf#630]
It would be good during debugging sessions if the user agent string contained the go-tuf version instead of the default Go user agent string. Also, during tuf client initializeation the client should be able to append their name, so the string becomes something like: `go-tuf/vx.y cosign/vx.y`.

cc @jku

**Comment by jku** [comment]
see also 
https://github.com/sigstore/sigstore-go/issues/143
https://github.com/theupdateframework/python-tuf/issues/2611

**Comment by steiza** [comment]
I attempted this with https://github.com/theupdateframework/go-tuf/pull/642.

See https://github.com/sigstore/sigstore-go/pull/216 for an example of how this would be used.

**Comment by kommendorkapten** [comment]
Done per https://github.com/theupdateframework/go-tuf/pull/642
