### ISSUE TITLE
Make repository.repositoryType public (repository.RepositoryType) 

### ISSUE THREAD

**Issue by eikenb** [theupdateframework/go-tuf#654]
The library uses `repository.repositoryType` as a way to manage the role metadata and interact with it while using the library. However the type is private and so cannot be used in any abstractions where you'd want to pass it as an argument.

Please consider making this type public so it can be used in abstractions.

Thanks.

**Comment by rdimitrov** [comment]
hey, @eikenb, thanks for reaching out 🙏 

Do you have a specific use case for using this type? I'm asking this because so far it has been used only in the `examples` and we were discussing moving this package there to simplify things. We can make it public of course while doing this.

**Comment by eikenb** [comment]
Moving the package to the examples area would be a great idea.

Right now, when working off the examples to help understand the package, using this type initially looks like a nice way to work with the roles as a group, when in fact it isn't, and that confuses things.

**Comment by rdimitrov** [comment]
Opened a PR to make the move 👍
