### ISSUE TITLE
TUF v0.7.0 tarball is 404

### ISSUE THREAD

**Issue by jas4711** [theupdateframework/go-tuf#659]
Hi.  Scrolling down to the release page of v0.7.0 and expanding the Assets and clicking on "Source code (tar.gz)" leads to this link:

https://github.com/theupdateframework/go-tuf/archive/refs/tags/v0.7.0.tar.gz

Which gives me a 404.  Scrolling down to 0.6.1 leads to this link:

https://github.com/theupdateframework/go-tuf/archive/refs/tags/v0.6.1.tar.gz

Which works fine.  What's going on here?  Could you make the v0.7.0 tarball downloadable?

Thanks,
Simon

**Comment by kommendorkapten** [comment]
The source archive is automatically generated by GitHub, so that's not something we can control. This appears to be a bug with GitHub Releases, I'll pull some strings.

As a workaround, if you look at the link here: https://github.com/theupdateframework/go-tuf/releases/tag/v0.7.0 the top link is the source archive, and it can be downloaded:

```shell
~/TMP % curl -L -O https://github.com/theupdateframework/go-tuf/releases/download/v0.7.0/tuf-0.7.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  531k  100  531k    0     0   684k      0 --:--:-- --:--:-- --:--:-- 6638k
~/TMP % ls -larth
total 1064
drwxr-x---+ 75 kommendorkapten  staff   2,3K  2 Dec 10:16 ../
drwxr-xr-x   3 kommendorkapten  staff    96B  2 Dec 11:32 ./
-rw-r--r--   1 kommendorkapten  staff   531K  2 Dec 11:32 tuf-0.7.0.tar.gz
kommendorkapten@m1m14-msft:~/TMP %
```

Would that work as a temporary fix?

**Comment by kommendorkapten** [comment]
The original link that caused a 404 is now working again, this was an issue with GitHub. Closing this.

**Comment by jas4711** [comment]
Confirmed solved, thank you!
