### ISSUE TITLE
client: Update FileLocalStore to support multiple repositories

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#68]
Clients should be able to use the same database file with multiple repositories (e.g Flynn users pulling images from arbitrary repositories).

This can be achieved by updating `FileLocalStore` to take a `namespace` argument which namespaces the boltdb lookups, and the remote repository URL can be used as the namespace.

**Comment by mnm678** [comment]
Multiple repository support can be added using [TAP 4](https://github.com/theupdateframework/taps/blob/master/tap4.md), out of scope for now.
