### ISSUE TITLE
Improve documentation around generating root keys

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#71]
The ["create signed root manifest" example](https://github.com/flynn/go-tuf/#create-signed-root-manifest) (which is the first thing repository maintainers need to do) needs to be clearer on why files need copying from a "root" box to a "repo" box, and that using multiple machines is optional (at the expense of reduced security).

**Comment by mnm678** [comment]
cc @asraa This might relate to the [cosign key generation](https://github.com/sigstore/cosign/pull/366)

**Comment by rdimitrov** [comment]
Closing since the code base changed and the goal of the project would be to focus on being a library first and not so much on providing a CLI client. 

There might be a CLI based on this, but it will live in a separate repository. 

Thanks for raising this! 👍
