### ISSUE TITLE
Support adding files to specific target manifests

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#88]
I would like to be able to make historic versions of the same file available for download to people who want it.

As a concrete example, users can download the latest version (say v3) of `my-binary` by running `client.Download("my-binary")`, but I would also like them to be able to download v2, perhaps like `client.DownloadVersion("my-binary", "v2")`.

I could handle this by adding version strings to files (e.g. have `my-binary` (the latest), `my-binary.v2`, `my-binary.v3` etc.) but this will lead to an ever growing targets manifest.

I could also point the client at a historic snapshot which contains a targets manifest with the correct versions in it, but this would be considered a downgrade attack and be rejected.

Instead I would like to maintain a collection of target manifests (one per version of my software), and requesting a specific version of a file would look in the relevant targets manifest (identified using custom metadata).

This isn't explicitly discussed in the [tuf spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt), but what is discussed is the ability for targets to [delegate trust for a subset of target files to other targets](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L252-L257). I plan to use this feature to achieve my goal, but the delegated roles would likely have the same keys as the top-level target, and would also have overlapping target responsibility (the end user would be responsible for determining which delegated manifest to download a given file from based on custom metadata).

On the repo side, the following changes would be needed:
- Add a `tuf role` command which will manage delegated roles (i.e. their keys and custom metadata)
- Add a `--role xxx` flag to `tuf add` to support adding files to specific delegated roles
- Update `tuf sign` to support signing delegated roles

On the client side:
- Expose enough role information to allow the client to choose a role based on custom metadata (the roles can be nested so this would likely be something like `role := client.FindRole(func(Role) bool)` to find a single role, or `roles := client.FindRoles(func(Role) bool, n int)` to find multiple roles)
- Add `role.Download(name string)` to download a file from a given delegated role

We need to decide whether our unintended use of delegated roles is a good idea, and whether it will be compatible with adding things like [hashed bins](https://github.com/theupdateframework/tuf/tree/develop/tuf#delegate-to-hashed-bins) in the future.

/cc @titanous

**Comment by vladimir-v-diaz** [comment]
FYI: It appears that the go-tuf implementation (by Jonathan Rudenberg and
Lewis Marshall) will be adding delegated roles.

--
vladimir.v.diaz@gmail.com
PGP fingerprint = ACCF 9DCA 73B9 862F 93C5  6608 63F8 90AA 1D25 3935
--

**Comment by mnm678** [comment]
Won't fix. Can use the naming scheme mentioned
